spring.application.name=AZOI

spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.url=jdbc:mariadb://localhost:3306/azoi?useSSL=false&serverTimezone=UTC

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

azoi.data.redis.worker-count=4

azoi.compiler.running-second=10
azoi.storage.root=/home/azathorpe/data/azoi
azoi.storage.problem-dir=/problems
azoi.storage.compile-dir=/compiled
azoi.storage.avatar-dir=/avatars
azoi.compiler.timeout-seconds=10
azoi.storage.submit-dir=/submit

azoi.judge.isolate-bin=/usr/local/bin/isolate
azoi.judge.tmp-root=/var/azoi-judge
azoi.judge.keep-sandbox-files=true
azoi.judge.runningOnSandBox=false

#TODO: 从环境变量读
azoi.jwt.secret=2PQ1ZUysA7e35dNxhD7Ew3FOCq4BSHSoPVjPLVkZcgo=
azoi.jwt.expire=86400